-- 0. 创建系统用户表
CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'viewer'  -- 'admin' 或 'viewer'
);

-- 1. 创建成员表
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    invested_principal NUMERIC NOT NULL DEFAULT 0.0,
    total_shares NUMERIC NOT NULL DEFAULT 0.0
);

-- 2. 创建资产快照历史表
CREATE TABLE IF NOT EXISTS assets_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    hk NUMERIC NOT NULL DEFAULT 0.0,
    us NUMERIC NOT NULL DEFAULT 0.0,
    dividend NUMERIC NOT NULL DEFAULT 0.0,
    high_risk NUMERIC NOT NULL DEFAULT 0.0
);

-- 3. 创建净值历史表
CREATE TABLE IF NOT EXISTS nav_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    total_assets NUMERIC NOT NULL,
    total_shares NUMERIC NOT NULL,
    nav NUMERIC NOT NULL
);

-- 4. 创建资金流水交易表
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    member_id BIGINT NOT NULL REFERENCES members (id),
    type TEXT NOT NULL,  -- 'INIT' 或 'INVEST' 或 'ADJUST'
    amount NUMERIC NOT NULL,
    nav NUMERIC NOT NULL,
    shares NUMERIC NOT NULL
);

-- 初始管理员数据 (admin / admin123)
-- 您可以在 Supabase UI 执行这段或者在这边一起执行
INSERT INTO app_users (username, password_hash, role)
VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'admin')
ON CONFLICT (username) DO NOTHING;

-- 初始净值种子数据（总资产=0, 总份额=0, 初始净值=1.0）
-- 系统要求 nav_history 至少有一条记录才能正常运行
INSERT INTO nav_history (total_assets, total_shares, nav)
SELECT 0, 0, 1.0
WHERE NOT EXISTS (SELECT 1 FROM nav_history);
